#############################################
# This script generates proportions of 
# highly related parasite sample comparisons
# using various 
# partitions (cities, states, times)
# thresholds for high relatedness (e.g. 0.01, 0.25, 0.5, 0.99)
# filters (unfiltered, filter by vertex, filter by edge)
#############################################

rm(list = ls())
load('../RData/All_results.RData') # This is generated by script Generate_and_plot_graph_components
eps = 0.01 # Some small number s.t. above 1-eps is considered 1
Summaries = c('mean', '2.5%', '97.5%') # Quanties of interest
Thresholds = c(0.01, 0.25, 0.5, 1-eps) # Thresholds for relatedness 
nrep = 100 # For bootstrap confidence intervals
set.seed(1) # For reproducibility

# Extract different ways of partitioning pairwise comparisons
cities = unique(All_results[["Unfiltered"]]$City12)
states = unique(All_results[["Unfiltered"]]$State12)
times = sort(unique(All_results[["Unfiltered"]]$time_bins))


# Result stores
proportions_cities = array(0, dim = c(length(Summaries),length(cities),length(Thresholds),length(All_results)), 
                                     dimnames = list(Summaries,cities,Thresholds,names(All_results)))
proportions_states = array(0, dim = c(length(Summaries),length(states),length(Thresholds),length(All_results)), 
                           dimnames = list(Summaries,states,Thresholds,names(All_results)))
proportions_times = array(0, dim = c(length(Summaries),length(times),length(Thresholds),length(All_results)), 
                                     dimnames = list(Summaries,times,Thresholds,names(All_results)))

# Function to return mean and CIs given inds and CI_bound (i.e. lower 2.5% or upper 97.5%)
return_mean_CIs = function(inds, bound){
  Mean = mean(X[inds, bound] >= threshold)
  prop_bootstrapped = sapply(1:nrep, function(b){
    booti_ind = sample(inds, length(inds), replace = T)
    mean(X[booti_ind, bound] >= threshold)})
  CIs = quantile(prop_bootstrapped, probs = c(0.025, 0.975))
  return(c('mean' = Mean, CIs))
}


for(l in names(All_results)){
  
  X = All_results[[l]]
  
  for(threshold in Thresholds){
    
    # If interested in clones, consider upper bound (i.e. is r-estimate statistically indistinguishable from 1), 
    # otherwise consider lower bound (i.e. is r-estimate statistically distinguishable from threshold)
    Bound = ifelse(threshold >= 1-eps, 'r97.5.', 'r2.5.') 
    
    # Calculate proportions over city comparisons 
    prop_cities = sapply(cities, function(x){
      return_mean_CIs(which(X$City12 == x), Bound)
    })
    
    # Calculate proportions over state comparisons 
    prop_states = sapply(states, function(x){
      return_mean_CIs(which(X$State12 == x), Bound)
    })
    
    # Calculate proportions over time comparisons 
    prop_times = sapply(as.character(times), function(x){
      return_mean_CIs(which(X$time_bins == as.numeric(x)), Bound)
    })
    
    proportions_cities[,,as.character(threshold), l] = prop_cities
    proportions_states[,,as.character(threshold), l] = prop_states
    proportions_times[,,as.character(threshold), l] = prop_times
}}

save(proportions_cities, proportions_states, proportions_times, 
     file = '../RData/proportions_sensitivities.RData')


