##############################################################################
#' Script to compare the extended clonal components generated by
#' Generate_components.R to the original clonal components reported in Taylor et
#' al. 2020,  to see how FSVC sids cluster with DE sids.
#'
#' LCI threshold of zero: 41 identical and 5 extended
#'
#' LCI threshold of 0.75: 45 identical and 1 extended (probably most reliable)
#'
#' LCI threshold of 0.95: 9 broken, 36 identical, 1 extended (breaks up 9 of the
#' original)
##############################################################################
rm(list = ls())
load(file = "../../RData/Clonal_components.RData")
CC_original <- Clonal_components

LCI_threshold <- 0.75 # Toggle between 0, 0.75 and 0.95 (make no difference)
load(file = sprintf("../../RData/Clonal_components_extended_all_LCIthrehold_%s.RData", LCI_threshold))
CC_extended <- Clonal_components

length(CC_extended)
length(CC_original)
all(unlist(CC_original) %in% unlist(CC_extended)) # Check all are within

# Define stores to categorise clonal components reported in Taylor et al. 2020
identical_components <- list()
extended_components <- list()
broken_components <- list()
  
# Cartegorise each of the clonal components reported in Taylor et al. 2020
for(i in names(CC_original)){
  for(j in names(CC_extended)){
    if(setequal(CC_original[[i]],CC_extended[[j]])) {
      identical_components[[i]][[j]] <- "Equal"
    } else if (all(CC_original[[i]] %in% CC_extended[[j]])) {
      extended_components[[i]][[j]][["original"]] <- CC_original[[i]]
      extended_components[[i]][[j]][["additional"]] <- setdiff(CC_extended[[j]],CC_original[[i]])
    } else {
      intersecting_sids <- intersect(CC_original[[i]],CC_extended[[j]])
      if(length(intersecting_sids) > 0) {
        broken_components[[i]][[j]][["intersect"]] <- intersecting_sids
        broken_components[[i]][[j]][["additional"]] <- setdiff(CC_extended[[j]],CC_original[[i]])
      } else {
        next()
      }
    }
  }
}

# Category breakdown
length(broken_components)
length(identical_components) 
length(extended_components) 

# Inspect
identical_components_key <- sapply(identical_components, names)
identical_components_key
broken_components 
extended_components 

# Inspect metadata
load(sprintf('../../RData/metadata_extended.RData'))
extended_components_metadata <- lapply(extended_components, function(x){
  metadata[unlist(x), ]
})
extended_components_metadata



